### ISSUE TITLE
Logging into "Production" gives an error

### ISSUE THREAD

**Issue by mikeumus** [Developer-Autodesk/model.derivative.api-nodejs-sample#1]
Logging in with the production option gives this error:

```
{"developerMessage":"The authorization code/refresh token is expired or invalid/redirect_uri 
must have the same value as in the authorization request.","userMessage":"","errorCode":
"AUTH-004","more info":"http://developer-stg.api.autodesk.com/documentation/v1/errors/AUTH-004"}`
```

and this in the Chrome Dev console this error:

```
http://modelderivative.herokuapp.com/api/autodesk/callback?code=excGmty-
X79Yt51Tf8J3PmKu8xE08Bncg7X9eRBV
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

:smile: :beetle:

**Comment by mikeumus** [comment]
@shiya, and what's the difference between this and the "[data.management.api-nodejs-sample](https://github.com/Developer-Autodesk/data.management.api-nodejs-sample)" ? It's still doing the SVF model derivative behind the scenes.

**Comment by cyrillef** [comment]
Hi,

as a 3rd party developer, you must be using the Production environment, and not staging. I know this is confusing that the sample choose staging per default, but I guess this is because the API came very late and we were experimenting the API on staging. I'll ask for Staging, and Dev to be removed.

**Comment by cyrillef** [comment]
"data.management.api-nodejs-sample" was supposed to primiraly show the DM API, while it may use the derivative service as well. We will rationalize the samples soon by using proper NPM packages.

**Comment by mikeumus** [comment]
Hi @cyrillef, thanks for the answers but this was an error message from the "Production" tab as the title implies, just wanted to report it. It happened a couple times with a friend and I trying to login.

**Comment by cyrillef** [comment]
Ok, I'll ask @adamenagy / @shiya to verify their code
Thx for letting us know

**Comment by mikeumus** [comment]
You're welcome @cyrillef. Thank you for the follow up :smiley: .
